# Tarefa 06 de Álgebra Linear Computacional

Atividade sobre Ortogonalização de Gram-Schmidt.

* **Aluna:** Bárbara Neves
* **Matrícula:** 507526

### Descrição

Implemente o método de **Ortogonalização de Gram-Schmidt** e faça o que se pede:
1. Dado um conjunto de $n$ vetores do $\mathbb{R}^{m}$ com $n < m$, usando o método da [Tarefa 05](https://drive.google.com/file/d/1wnk3UwHv07qoq9CqduD3xPaAfGVVmwXn/view?usp=sharing), estenda esse conjunto de vetores para achar uma base do $\mathbb{R}^{m}$.
2. Use o processo de Ortogonalização de Gram-Schmidt sobre a base estendida, para encontrar uma base ortonormal do $\mathbb{R}^{m}$.

# Imports

In [ ]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

# Ortogonalização

<center>
  <img src="https://bvanderlei.github.io/jupyter-guide-to-linear-algebra/_images/Span_big.png" />
</center>

Algumas das aplicações mais importantes de produtos internos envolvem encontrar e usar conjuntos de vetores que são mutuamente **ortogonais**. 

Um conjunto de vetores não nulos $\{\vec{u_1}, \vec{u_2}, \vec{u_3}, \cdots, \vec{u_n}\}$ é mutuamente ortogonal se $\vec{u_i} \cdot \vec{u_j} = 0$ sempre que $i \neq j$.

Isso significa simplesmente que cada vetor no conjunto é ortogonal a todos os outros vetores do conjunto. Se um conjunto de vetores é mutuamente ortogonal e todo vetor no conjunto é um vetor unitário, dizemos que o conjunto é **ortonormal**. 

\\

---

\\

> Conjuntos ortonormais devem ser **linearmente independentes**, então faz sentido pensar neles como uma base para algum subespaço vetorial. 
>
> - **Qualquer coleção de vetores das bases padrão do $\mathbb{R}_n$ são conjuntos ortonormais.** 
>
> Por exemplo, o conjunto de vetores $\{\vec{e_1}, \vec{e_4}, \vec{e_5}\}$ abaixo da base do $\mathbb{R}_5$ forma uma base ortonormal para um subespaço de $\mathbb{R}_5$.

\\

\begin{gather*} 
  \vec{e_1} = \begin{bmatrix}
  1 \\
  0 \\
  0 \\
  0 \\
  0 
  \end{bmatrix} 
  \qquad
  \vec{e_4} = \begin{bmatrix}
  0 \\
  0 \\
  0 \\
  1 \\
  0
  \end{bmatrix}
  \qquad
  \vec{e_5} = \begin{bmatrix}
  0 \\
  0 \\
  0 \\
  0 \\
  1
  \end{bmatrix}
\end{gather*}

\\

# Processo de *Gram-Schmidt*

A **Ortogonalização ou o Processo de *Gram Schmidt*** é usado para transformar um conjunto de vetores linearmente independentes em um conjunto de vetores ortonormais formando uma base ortonormal. 

Dado um conjunto de vetores linearmente independentes $\{\vec{v_1}, \vec{v_2}, \vec{v_3}, \cdots, \vec{v_n}\}$, o algoritmo de Gram-Schmidt produz um conjunto ortonormal de vetores $\{\vec{u_1}, \vec{u_2}, \vec{u_3}, \cdots, \vec{u_n}\}$ tal que o intervalo de $\{\vec{u_1}, \vec{u_2}, \vec{u_3}, \cdots, \vec{u_n}\}$ é igual ao intervalo de $\{\vec{v_1}, \vec{v_2}, \vec{v_3}, \cdots, \vec{v_n}\}$. 

\\

---

\\

O algoritmo funciona da seguinte forma:

1. $\vec{v_1}$ é dimensionado para unidade de comprimento e se torna $\vec{u_1}$.
2. A projeção de $\vec{v_2}$ na direção de $\vec{u_1}$ é subtraída de $\vec{v_2}$. O vetor resultante é dimensionado para unidade de comprimento e se torna $\vec{u_2}$.
3. As projeções de $\vec{v_3}$ nas direções de $\vec{u_1}$ e $\vec{u_2}$ são subtraídas de $\vec{v_3}$. O vetor resultante é dimensionado para unidade de comprimento e se torna $\vec{u_3}$.
4. Continue aplicando um procedimento semelhante para todos os $n$ vetores. Em geral, as projeções de $\vec{v_k}$ nas direções de $\vec{u_1}, \vec{u_2}, \cdots, \vec{u_{k-1}}$ são subtraídas de $\vec{v_k}$ e o vetor resultante é dimensionado para unidade de comprimento para se tornar $\vec{u_k}$.


In [ ]:
def rref(A):
  '''
  Retorna a RREF da matriz, o rank e o valor do espaço nulo da matriz
  '''
  n, m = A.shape
  U = np.array(A)
  
  min_dim = min(m, n)
  i = 0
  while i < min_dim:
    k = np.argmax(np.abs(U[i:, i])) + i
    U[[i, k]] = U[[k, i]]

    pivot = i
    while U[i, pivot] == 0 and pivot < min_dim - 1:
      pivot += 1

    if pivot < min_dim:
      for j in range(n):
        if j != i and U[i, pivot] != 0:
          ratio = U[j, pivot] / U[i, pivot]
          U[j, :] = (U[j, :] - ratio * U[i, :])
      
      if U[i, pivot] != 0:
        U[i, :] = U[i, :] / U[i, pivot]
    i = pivot + 1

  rank = sum(any(row) for row in U) 
  nullity = A.shape[1] - rank 

  return U, rank, nullity

In [ ]:
def gram_schmidt(A):
  m = A.shape[1]
  Q = np.zeros(A.shape)
  temp_vector = np.zeros(m)

  Q[:, 0] = A[:, 0] / np.linalg.norm(A[:, 0], ord=2)

  for i in range(1, m):
    q = Q[:, :i]
    temp_vector = np.sum(np.sum(q * A[:, i, None], axis=0) * q, axis=1)
    Q[:, i] = A[:, i] - temp_vector
    Q[:, i] /= np.linalg.norm(Q[:, i], ord=2)

  return Q

## O que iremos resolver?







### Questão 1 

Dado um conjunto de $n$ vetores do $\mathbb{R}^{m}$ com $n < m$, usando o método da [Tarefa 05](https://drive.google.com/file/d/1wnk3UwHv07qoq9CqduD3xPaAfGVVmwXn/view?usp=sharing), estenda esse conjunto de vetores para achar uma base do $\mathbb{R}^{m}$.

> Para isso, iremos mostrar se o conjunto de vetores $\left\{ \begin{bmatrix}
0 \\
2 \\
1 \\
0
\end{bmatrix},
\begin{bmatrix}
1 \\
-1 \\
0 \\
0
\end{bmatrix},
\begin{bmatrix}
1 \\
2 \\
0 \\
-1
\end{bmatrix},
\begin{bmatrix}
1 \\
0 \\
0 \\
1
\end{bmatrix}\right\}$ é uma base do $\mathbb{R}^{4}$.

Exemplo retirado do seguinte [*link*](https://faculty.millikin.edu/~jstickles/ma303/gramschmidtkey.pdf).

In [ ]:
A = np.array([
  [0, 1, 1, 1],
  [2, -1, 2, 0],
  [1, 0, 0, 0],
  [0, 0, -1, 1]
], dtype='float32')

- **Solução:**

> Como a RREF da base é a **matriz identidade**, concluímos que este conjunto de vetores é sim uma base do $\mathbb{R}^{4}$.

In [ ]:
rref_, rank, nullity = rref(A)

In [ ]:
print('RREF da base =\n{}'.format(rref_))
print('Rank da base = {}'.format(rank))
print('Nullity da base = {}'.format(nullity))

RREF da base =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1.  0.]
 [ 0.  0.  0.  1.]]
Rank da base = 4
Nullity da base = 0


### Questão 2

Use o processo de Ortogonalização de Gram-Schmidt sobre a base estendida, para encontrar uma base ortonormal do $\mathbb{R}^{m}$.

> Assim, usando o processo de Gram-Schmidt, se $\left\{ \begin{bmatrix}
0 \\
2 \\
1 \\
0
\end{bmatrix},
\begin{bmatrix}
1 \\
-1 \\
0 \\
0
\end{bmatrix},
\begin{bmatrix}
1 \\
2 \\
0 \\
-1
\end{bmatrix},
\begin{bmatrix}
1 \\
0 \\
0 \\
1
\end{bmatrix}\right\}$ for uma base do $\mathbb{R}^{4}$, iremos transformá-la em uma base ortonormal do $\mathbb{R}^{4}$.

- **Solução:**

> Usando a Ortogonalização de Gram-Schmidt e normalizando a matriz, temos a seguinte **base ortonormal do $\boldsymbol{\mathbb{R}^{4}}$**.

In [ ]:
_A = gram_schmidt(A)

_A

array([[ 0.  ,  0.91,  0.32,  0.26],
       [ 0.89, -0.18,  0.32,  0.26],
       [ 0.45,  0.37, -0.63, -0.52],
       [ 0.  ,  0.  , -0.63,  0.77]])

In [ ]:
# Checando se a nova matriz com o Gram-Schmidt é ortonormal
_A @ _A.T

array([[ 1.,  0., -0., -0.],
       [ 0.,  1., -0., -0.],
       [-0., -0.,  1.,  0.],
       [-0., -0.,  0.,  1.]])