# Tarefa 05 de Álgebra Linear Computacional

Atividade sobre RREF.

* **Aluna:** Bárbara Neves
* **Matrícula:** 507526

### Descrição

Implemente o método para determinar o **RREF** de uma matriz $m \times n$ e, testando em matrizes com $m > n$, $m < n$ e $m = n$, determine:
1. RREF da matriz.
2. O posto da matriz (*rank*).
3. A dimensão do espaço nulo da matriz.

# Imports

In [ ]:
import numpy as np
import sympy

# *Reduced Row Echelon Form*

Uma matriz está na sua ***Reduced Row Echelon Form* (RREF)** se tiver as seguintes propriedades:

- A primeira entrada diferente de zero em cada linha é 1. Essas entradas são chamadas de pivôs (como de praxe).
- Cada pivô está localizado à direita dos pivôs em todas as linhas acima dele.
- As entradas acima e abaixo de cada pivô possuem zeros.
- As linhas que são formadas por zeros estão localizadas abaixo de outras linhas.

Praticamente, qualquer matriz pode ser transformada para a RREF usando Eliminação de Gauss.

\\

---

\\

Abaixo estão alguns exemplos de matrizes que estão na RREF.

\\

\begin{gather*} 
  \begin{bmatrix}
  1 & 0 & 0 & * \\
  0 & 1 & 0 & *  \\
  0 & 0 & 1 & *
  \end{bmatrix} \\\\
  \begin{bmatrix}
  1 & * & 0 & 0 & * \\
  0 & 0 & 1 & 0 & * \\
  0 & 0 & 0 & 1 & * \\
  0 & 0 & 0 & 0 & 0
  \end{bmatrix} \\\\
  \begin{bmatrix}
  1 & * & 0 & 0 & * & * \\
  0 & 0 & 1 & 0 & * & * \\
  0 & 0 & 0 & 1 & * & *
  \end{bmatrix}
\end{gather*}

\\

---

### ***Rank***

O **posto (*rank*)** da matriz trata-se do número de linhas diferentes de zero na RREF. Para encontrar o *rank*, precisamos executar as seguintes etapas:

1. Encontrar a RREF da matriz dada.
2. Contar o número de linhas não compostas inteiramente de zeros.

---

### ***Nullity*** 

A dimensão do espaço nulo de uma matriz, chamada de nulidade ou *nullity*, pode ser definida como o número de vetores presentes no espaço nulo da matriz. Isto é, o espaço nulo de uma matriz $A$ consiste em todos os vetores $B$ tais que $AB = 0$, sendo que $B$ não possui zeros.

Uma forma de verificar isso é calculando a diferença entre o número de colunas pelo valor do *rank*.

In [ ]:
def rref(A):
  '''
  Retorna a RREF da matriz, o rank e o valor do espaço nulo da matriz
  '''
  n, m = A.shape
  U = np.array(A)
  
  min_dim = min(m, n)
  i = 0
  while i < min_dim:
    k = np.argmax(np.abs(U[i:, i])) + i
    U[[i, k]] = U[[k, i]]

    pivot = i
    while U[i, pivot] == 0 and pivot < min_dim - 1:
      pivot += 1

    if pivot < min_dim:
      for j in range(n):
        if j != i and U[i, pivot] != 0:
          ratio = U[j, pivot] / U[i, pivot]
          U[j, :] = (U[j, :] - ratio * U[i, :])
      
      if U[i, pivot] != 0:
        U[i, :] = U[i, :] / U[i, pivot]
    i = pivot + 1

  rank = sum(any(row) for row in U) 
  nullity = A.shape[1] - rank 

  return U, rank, nullity

### Exemplo 1: Matriz $m > n$

\begin{gather*} 
  A_1 = \begin{bmatrix}
  1 & 0 & 0 \\ 
  0 & 0 & 0 \\
  0 & 1 & 0 \\
  0 & 0 & 1
  \end{bmatrix} 
\end{gather*}


In [ ]:
A_1 = np.array([
  [1, 0, 0],
  [0, 0, 0],
  [0, 1, 0],
  [0, 0, 1]
], dtype='float32')

In [ ]:
rref_1, rank_1, nullity_1 = rref(A_1)

In [ ]:
print('RREF da matriz A1 =\n{}'.format(rref_1))
print('Rank da matriz A1 = {}'.format(rank_1))
print('Nullity da matriz A1 = {}'.format(nullity_1))

RREF da matriz A1 =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
Rank da matriz A1 = 3
Nullity da matriz A1 = 0


In [ ]:
# Segue a comparação com os métodos da biblioteca SymPy
print('RREF da matriz A1 com o SymPy =\n{}'.format(sympy.Matrix(A_1).rref()[0]))
print('Rank da matriz A1 com o SymPy = {}'.format(sympy.Matrix(A_1).rank()))
print('Nullity da matriz A1 com o Sympy = {}'.format(sympy.Matrix(A_1).rref()[0].shape[1] - sympy.Matrix(A_1).rank()))

RREF da matriz A1 com o SymPy =
Matrix([[1, 0, 0], [0.0, 1, 0], [0.0, 0.0, 1], [0.0, 0.0, 0.0]])
Rank da matriz A1 com o SymPy = 3
Nullity da matriz A1 com o Sympy = 0


### Exemplo 2: Matriz $m < n$

\begin{gather*} 
  A_2 = \begin{bmatrix}
  1 & 0 & 4 & 0 & 6 \\ 
  0 & 0 & 0 & 1 & 3 \\ 
  0 & 1 & 0 & 0 & 7
  \end{bmatrix} 
\end{gather*}


In [ ]:
A_2 = np.array([
  [1, 0, 4, 0, 6],
  [0, 0, 0, 1, 3],
  [0, 1, 0, 0, 7]
], dtype='float32')

In [ ]:
rref_2, rank_2, nullity_2 = rref(A_2)

In [ ]:
print('RREF da matriz A2 =\n{}'.format(rref_2))
print('Rank da matriz A2 = {}'.format(rank_2))
print('Nullity da matriz A2 = {}'.format(nullity_2))

RREF da matriz A2 =
[[1. 0. 4. 0. 6.]
 [0. 1. 0. 0. 7.]
 [0. 0. 0. 1. 3.]]
Rank da matriz A2 = 3
Nullity da matriz A2 = 2


In [ ]:
# Segue a comparação com os métodos da biblioteca SymPy
print('RREF da matriz A2 com o SymPy =\n{}'.format(sympy.Matrix(A_2).rref()[0]))
print('Rank da matriz A2 com o SymPy = {}'.format(sympy.Matrix(A_2).rank()))
print('Nullity da matriz A2 com o Sympy = {}'.format(sympy.Matrix(A_2).rref()[0].shape[1] - sympy.Matrix(A_2).rank()))

RREF da matriz A2 com o SymPy =
Matrix([[1, 0, 4.00000, 0, 6.00000], [0.0, 1, 0, 0, 7.00000], [0.0, 0.0, 0.0, 1, 3.00000]])
Rank da matriz A2 com o SymPy = 3
Nullity da matriz A2 com o Sympy = 2


### Exemplo 3: Matriz $m = n$

\begin{gather*} 
  A_3 = \begin{bmatrix}
  4 & 0 & 1 \\ 
  2 & 0 & 2 \\ 
  3 & 0 & 3 \\
  \end{bmatrix} 
\end{gather*}


In [ ]:
A_3 = np.array([
  [4, 0, 1],
  [2, 0, 2],
  [3, 0, 3]
], dtype='float32')

In [ ]:
rref_3, rank_3, nullity_3 = rref(A_3)

In [ ]:
print('RREF da matriz A3 =\n{}'.format(rref_3))
print('Rank da matriz A3 = {}'.format(rank_3))
print('Nullity da matriz A3 = {}'.format(nullity_3))

RREF da matriz A3 =
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
Rank da matriz A3 = 2
Nullity da matriz A3 = 1


In [ ]:
# Segue a comparação com os métodos da biblioteca SymPy
print('RREF da matriz A3 com o SymPy =\n{}'.format(sympy.Matrix(A_3).rref()[0]))
print('Rank da matriz A3 com o SymPy = {}'.format(sympy.Matrix(A_3).rank()))
print('Nullity da matriz A3 com o Sympy = {}'.format(sympy.Matrix(A_3).rref()[0].shape[1] - sympy.Matrix(A_3).rank()))

RREF da matriz A3 com o SymPy =
Matrix([[1, 0, 0], [0, 0, 1], [0, 0, 0]])
Rank da matriz A3 com o SymPy = 2
Nullity da matriz A3 com o Sympy = 1
