# Tarefa 10 de Álgebra Linear Computacional

Atividade sobre Método de Householder (Transformação de Similaridade).

* **Aluna:** Bárbara Neves
* **Matrícula:** 507526


### Descrição

Implementar a Decomposição QR de uma matriz $n \times n$.

1. Entrar com uma matriz qualquer $A_{n \times n}$.
2. Encontrar as matrizes $Q$ (ortogonal) e $R$ (triangular superior) tal que $A = QR$.
3. Imprimir as matrizes $Q$ e $R$ e mostrar que o produto $QR = A$.

# Imports

In [ ]:
import numpy as np
from scipy.linalg import qr
np.set_printoptions(precision=2, suppress=True)

import warnings
warnings.filterwarnings("ignore")

# Decomposição QR

O **Método da Decomposição QR** de uma matriz, como o próprio nome diz, decompõe a matriz no produto entre uma matriz ortogonal e uma matriz triangular.

Uma Decomposição QR de uma matriz $A$ qualquer assume a forma:

\begin{gather*} 
  A = QR
\end{gather*}

Onde

- $Q$ é uma matriz ortogonal, então $Q^TQ = I$; e, 
- $R$ é uma matriz triangular superior.

Usaremos uma parte do Método de Householder para calculo da Decomposição QR neste trabalho, feito na [Tarefa 9](https://drive.google.com/file/d/1FFGhAOYb8WPzoEwqkvRxFQbIJtWPxa91/view?usp=sharing), já que uma matriz de Householder é uma matriz ortogonal.







In [ ]:
def build_H(A, j):
  A = A.copy()
  s = A.shape[0]
  v = A[:, j]
  v[0: j] = 0
  w = np.zeros(s)
  w[j] = np.linalg.norm(v)
  
  if v[j] > 0: 
    w[j] = -np.linalg.norm(v)    
  
  N = v - w
  n = N / np.linalg.norm(N)
  H = np.eye(s) - 2 * (n[:, None] @ n[None, :])
  
  return H

In [ ]:
def QR_Decomposition(A):
  R = A.copy()
  n = R.shape[0]
  Q = np.eye(n)
  
  for j in range(n - 1):
    Qj = build_H(R, j)
    R = Qj @ R
    Q = Q @ Qj
  
  return Q, R

def diag_sign(A):
  D = np.diag(np.sign(np.diag(A)))
  return D

def adjust_sign(Q, R):
  D = diag_sign(Q)

  Q[:, :] = Q @ D
  R[:, :] = D @ R

  return Q, R

## Exemplo 1: Matriz $A_{1 \; 2 \times 2}$

\begin{gather*} 
  A_1 = \begin{bmatrix}
  0 & 2 \\
  2 & 3
  \end{bmatrix} 
\end{gather*}

Exemplo pequeno e bastante simples retirado do seguinte [*link*](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter15.03-The-QR-Method.html).

In [ ]:
A_1 = np.array([
  [0, 2],
  [2, 3]
], dtype='float32')

In [ ]:
Q_1, R_1 = adjust_sign(*QR_Decomposition(A_1))

In [ ]:
print('Q = \n{}\n'.format(Q_1))
print('R = \n{}\n'.format(R_1))

b_1 = np.dot(Q_1, R_1)
print('QR = \n{}'.format(b_1))

Q = 
[[0. 1.]
 [1. 0.]]

R = 
[[2. 3.]
 [0. 2.]]

QR = 
[[0. 2.]
 [2. 3.]]


In [ ]:
# Solução com a função pronta do Scipy para comparação
np_solver_Q1, np_solver_R1 = qr(A_1)

print('Q = \n{}\n'.format(np_solver_Q1))
print('R = \n{}\n'.format(np_solver_R1))

np_solver_b1 = np.dot(np_solver_Q1, np_solver_R1)
print('QR = \n{}'.format(np_solver_b1))

Q = 
[[ 0. -1.]
 [-1.  0.]]

R = 
[[-2. -3.]
 [ 0. -2.]]

QR = 
[[0. 2.]
 [2. 3.]]


## Exemplo 2: Matriz $A_{2 \; 3 \times 3}$

\begin{gather*} 
  A_1 = \begin{bmatrix}
  1 & 1 & 0 \\
  1 & 0 & 1 \\
  0 & 1 & 1
  \end{bmatrix} 
\end{gather*}

Exemplo pequeno e bastante simples retirado do seguinte [*link*](https://python.quantecon.org/qr_decomp.html).

In [ ]:
A_2 = np.array([
  [1, 1, 0], 
  [1, 0, 1], 
  [0, 1, 1]
], dtype='float32')

In [ ]:
Q_2, R_2 = adjust_sign(*QR_Decomposition(A_2))

In [ ]:
print('Q = \n{}\n'.format(Q_2))
print('R = \n{}\n'.format(R_2))

b_2 = np.dot(Q_2, R_2)
print('QR = \n{}'.format(b_2))

Q = 
[[0. 1.]
 [1. 0.]]

R = 
[[2. 3.]
 [0. 2.]]

QR = 
[[0. 2.]
 [2. 3.]]


In [ ]:
# Solução com a função pronta do Scipy para comparação
np_solver_Q2, np_solver_R2 = qr(A_2)

print('Q = \n{}\n'.format(np_solver_Q2))
print('R = \n{}\n'.format(np_solver_R2))

np_solver_b2 = np.dot(np_solver_Q2, np_solver_R2)
print('QR = \n{}'.format(np_solver_b2))

Q = 
[[-0.71  0.41 -0.58]
 [-0.71 -0.41  0.58]
 [-0.    0.82  0.58]]

R = 
[[-1.41 -0.71 -0.71]
 [ 0.    1.22  0.41]
 [ 0.    0.    1.15]]

QR = 
[[1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 1.]]


<!--- Matrizes simétricas -> $A = A^T$ (definição)

Toda matriz simétrica com coeficientes reais (cujos elementos são reais) os autovalores dela necessariamente são números reais -> Não pode ser número imaginário 

Matrizes simétricas possuem multiplicidade algébrica igual a multiplicidade geométrica -> Os autovalores mesmo repetidos vão ter o número suficiente de autovetores associados a eles

(A, x, eps) -> A = matriz A; x = vetor inicial; eps = tolerância (número que vai servir para o critério de parada)
!-->