# Tarefa 12 de Álgebra Linear Computacional

Atividade sobre Decomposição SVD.

* **Aluna:** Bárbara Neves
* **Matrícula:** 507526


### Descrição

Implementar a **Decomposição SVD** de uma matriz qualquer $A_{m \times n}$.
1. Entrar com a matriz.
2. Encontrar e imprimir as matrizes $U$, $\Sigma$, $V$.
3. Mostrar que o produto $U \cdot \Sigma \cdot V^T = A$.

> **Obs.:** Quando necessário, use extensão de base e Ortogonalização de Gram-Schmidt para encontrar $U$ ou $V$ completas.

# Imports

In [1]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

import warnings
warnings.filterwarnings("ignore")

# Decomposição SVD

A **Singular Value Decomposition (SVD)** é um método de fatoração de matrizes que generaliza a autodecomposição de uma matriz quadrada ($n \times n$) para qualquer matriz ($m \times n$) (fonte).

A fórmula geral do SVD é:

\begin{gather*} 
  A = U \Sigma V^T
\end{gather*}

Onde temos que:
- $A$ é a matriz original que queremos decompor;
- $U$ é uma matriz singular à esquerda (as colunas são vetores singulares à esquerda). As colunas $U$ contêm autovetores da matriz $AA^t$;
- $\Sigma$ é uma matriz diagonal contendo autovalores;
- $V$ é a matriz singular à direita (colunas são vetores singulares à direita). As colunas $V$ contêm autovetores da matriz $A^tA$.

\\

<center>
  <img width="500" src="https://miro.medium.com/max/1400/1*mo8loFarEKeNeVX49205-g.png" />
</center>

\\



In [2]:
def svd(A, tolerance=1e-10):
  AtA = A.T @ A
  
  S, V = np.linalg.eig(AtA)
  S = S[np.abs(S) > tolerance]
  S = np.sqrt(S)
  
  AAt = A @ A.T
  _, U = np.linalg.eig(AAt)
  
  return U, S, V

## Exemplo 1

### Matriz $A$

\begin{gather*} 
  A = \begin{bmatrix}
  1 & 0 & -1 \\
  -2 & 1 & 4
  \end{bmatrix}
\end{gather*}

\\

In [3]:
A = np.array([
  [1, 0, -1],
  [-2, 1, 4]
], dtype='float32')

In [4]:
U, S, V = svd(A)

U, S, V

(array([[-0.9606,  0.2779],
        [-0.2779, -0.9606]], dtype=float32),
 array([4.7682, 0.5137], dtype=float32),
 array([[-0.4612,  0.7878,  0.4082],
        [ 0.2015,  0.5411, -0.8165],
        [ 0.8641,  0.2943,  0.4082]], dtype=float32))

## Exemplo 2

### Matriz $B$

\begin{gather*} 
  B = \begin{bmatrix}
  3 & 2 \\
  0 & 2
  \end{bmatrix}
\end{gather*}

\\

In [5]:
B = np.array([
  [3, 2],
  [0, 2]
], dtype='float32')

In [6]:
U, S, V = svd(B)

U, S, V

(array([[ 0.9347, -0.3554],
        [ 0.3554,  0.9347]], dtype=float32),
 array([3.8106, 1.5745], dtype=float32),
 array([[ 0.7359, -0.6771],
        [ 0.6771,  0.7359]], dtype=float32))

In [7]:
U * S @ V.T

array([[3., 2.],
       [0., 2.]], dtype=float32)