# Tarefa 09 de Álgebra Linear Computacional

Atividade sobre Método de Householder (Transformação de Similaridade).

* **Aluna:** Bárbara Neves
* **Matrícula:** 507526


### Descrição

Implementar o **Método de Householder** e fazer o que se pede:

1. imprima a matriz original (teste matrizes $n \times n$ com $n > 6$,  simétricas e não simétricas);
2. em cada passo, 
  - imprima a matriz de Householder, 
  - a matriz modificada pela transformação de similaridade, e 
  - a matriz de householder acumulada;
3. no final do *loop* de execução, imprima 
    - a matriz de saída (tridiagonal se a matriz de entrada for simétrica, ou *Upper-Hessemberg* se a matriz de entrada não for simétrica);
    - a matriz de Householder acumulada (final).

# Imports

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

import warnings
warnings.filterwarnings("ignore")

# Método de Householder

Trata-se de uma transformação de similaridade. Pode ser usado para encontrar os autovalores de uma matriz, mas possui outros usos fora desse processo. 

O método é normalmente usado para encontrar uma matriz tridiagonal simétrica $B$ que é semelhante a uma dada matriz simétrica $A$. 

### **Transformação de Householder**

Quando uma matriz $A$ passa por uma transformação de similaridade, é gerada uma matriz $B$ com os mesmos autovalores e com autovetores diferentes, mas relacionados entre si.

Assim, temos que

\begin{gather*} 
  A \xrightarrow[]{TS} B \;\; \textrm{tal que} \;\; \lambda(A) = \lambda(B)
\end{gather*}

\\

Considere $\Phi$ como sendo a matriz de autovetores de $A$ e $\Psi$ a matriz de autovetores de $B$. 

Como temos $B = P^{-1}AP$, a formúla da transformação de similaridade, podemos chegar a conclusão que $\Phi = P\Psi$.

\\

---

\\
A matriz de Householder $H$ é uma matriz ortogonal $(H^T = H^{-1})$ tal que:

\begin{align}
H = I - 2nn^T
\end{align}

onde $n$ é unitário. 

> $H$ é usada como a matriz $P$ da transformação de similaridade.

In [2]:
def build_H(A, j):
  A = A.copy()
  s = A.shape[0]
  v = A[:, j]
  v[0:j+1] = 0
  w = np.zeros(s)
  w[j+1] = np.linalg.norm(v)
  
  N = v - w
  n = N / np.linalg.norm(N)
  
  H = np.eye(s) - 2 * (n[:, None] @ n[None, :])
  
  return H

In [3]:
def householder(A):
  T = A.copy()
  n = T.shape[0]
  Hc = np.eye(n)
  
  for j in range(n - 2):
    H = build_H(T, j)
    print("------> Iteração {}:\n\n   Matriz Householder = \n {}\n".format(j + 1, H))
    T = H @ T @ H

    print("   Matriz A = \n {}\n".format(A))
    print("   Matriz Householder Acumulada = \n {}\n".format(Hc))
    
    Hc = Hc @ H

  return Hc, T

## Exemplo 1: Matriz Simétrica

In [4]:
def get_symmetric_matrix(n=7):
  b = np.random.randint(-100, 100 + 1, size=(n, n))
  return (b + b.T) / 2

In [5]:
A_1 = get_symmetric_matrix(n=7)

H_1, T_1 = householder(A_1)

------> Iteração 1:

   Matriz Householder = 
 [[ 1.    0.    0.    0.    0.    0.    0.  ]
 [ 0.   -0.03 -0.48  0.28 -0.37 -0.15  0.73]
 [ 0.   -0.48  0.78  0.13 -0.17 -0.07  0.34]
 [ 0.    0.28  0.13  0.92  0.1   0.04 -0.2 ]
 [ 0.   -0.37 -0.17  0.1   0.87 -0.05  0.26]
 [ 0.   -0.15 -0.07  0.04 -0.05  0.98  0.1 ]
 [ 0.    0.73  0.34 -0.2   0.26  0.1   0.48]]

   Matriz A = 
 [[-13.   -2.5 -37.5  22.  -28.5 -11.5  57. ]
 [ -2.5  29.  -35.   22.  -11.   49.5   3. ]
 [-37.5 -35.  -37.   78.   -5.   -8.5 -33. ]
 [ 22.   22.   78.   42.  -13.   29.   98.5]
 [-28.5 -11.   -5.  -13.   21.   56.  -39. ]
 [-11.5  49.5  -8.5  29.   56.   52.   58.5]
 [ 57.    3.  -33.   98.5 -39.   58.5  71. ]]

   Matriz Householder Acumulada = 
 [[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]

------> Iteração 2:

   Matriz Householder = 
 [[ 1.    0.    0.    0.    0.    0.    0.  ]
 [ 0.

In [6]:
print("Matriz tridiagonal = \n\n{}\n\nMatriz de Householder acumulada = \n\n{}".format(T_1, H_1))

Matriz tridiagonal = 

[[-13.    78.04  -0.     0.    -0.    -0.    -0.  ]
 [ 78.04  89.37  88.7    0.    -0.    -0.    -0.  ]
 [ -0.    88.7   56.52 110.65   0.    -0.     0.  ]
 [  0.     0.   110.65 -18.3   62.71   0.    -0.  ]
 [ -0.     0.    -0.    62.71   8.68  69.58  -0.  ]
 [ -0.    -0.    -0.    -0.    69.58  12.67  35.31]
 [ -0.    -0.    -0.     0.    -0.    35.31  29.05]]

Matriz de Householder acumulada = 

[[ 1.    0.    0.    0.    0.    0.    0.  ]
 [ 0.   -0.03  0.27  0.    0.18  0.    0.95]
 [ 0.   -0.48  0.71 -0.28 -0.14 -0.37 -0.19]
 [ 0.    0.28  0.24  0.78 -0.29 -0.4  -0.  ]
 [ 0.   -0.37 -0.14  0.33  0.8  -0.28 -0.12]
 [ 0.   -0.15  0.43  0.37  0.11  0.79 -0.15]
 [ 0.    0.73  0.4  -0.25  0.46 -0.07 -0.18]]


## Exemplo 2: Matriz Não Simétrica

In [7]:
n = 7

A_2 = np.random.randint(-100, 100 + 1, size=(n, n))

H_2, T_2 = householder(A_2)

------> Iteração 1:

   Matriz Householder = 
 [[ 1.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.12  0.36 -0.07 -0.71 -0.26  0.53]
 [ 0.    0.36  0.85  0.03  0.29  0.1  -0.22]
 [ 0.   -0.07  0.03  1.   -0.05 -0.02  0.04]
 [ 0.   -0.71  0.29 -0.05  0.43 -0.21  0.43]
 [ 0.   -0.26  0.1  -0.02 -0.21  0.93  0.16]
 [ 0.    0.53 -0.22  0.04  0.43  0.16  0.68]]

   Matriz A = 
 [[ -73    2   34   95   -2   83  -38]
 [  17  -72  -68   30  -63   26   52]
 [  49   56  -60  -46  -92   12  -35]
 [  -9    0  -16   85  -95  -80   44]
 [ -97   11    6  -61   29  -49   47]
 [ -35   14   71   51   19  -63   42]
 [  73   -3  -71    8  -74    7 -100]]

   Matriz Householder Acumulada = 
 [[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]

------> Iteração 2:

   Matriz Householder = 
 [[ 1.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.    0.    0.  ]
 [ 0.    

In [8]:
print("Matriz Upper Hessenberg = \n\n{}\n\nMatriz de Householder acumulada = \n\n{}".format(T_2, H_2))

Matriz Upper Hessenberg = 

[[-73.   -33.9  120.78  39.47 -33.95  -5.02   6.96]
 [136.87 -36.71  10.73 158.49  16.93 -74.65 -38.66]
 [ -0.   120.08  26.89  54.52  66.37  53.49 -64.93]
 [  0.     0.    91.84 -80.52 -32.82  54.84 -26.87]
 [  0.     0.    -0.    69.7  -18.33  93.39  -8.3 ]
 [ -0.     0.    -0.    -0.    31.73 -41.45 -67.51]
 [ -0.    -0.     0.    -0.    -0.     2.42 -30.88]]

Matriz de Householder acumulada = 

[[ 1.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.12  0.29 -0.28  0.66 -0.57  0.24]
 [ 0.    0.36  0.38 -0.54 -0.63 -0.2  -0.04]
 [ 0.   -0.07  0.81  0.14  0.2   0.44 -0.29]
 [ 0.   -0.71 -0.01 -0.61  0.02  0.26  0.23]
 [ 0.   -0.26  0.33  0.46 -0.32 -0.19  0.69]
 [ 0.    0.53 -0.08 -0.15  0.17  0.58  0.57]]


<!--- Matrizes simétricas -> $A = A^T$ (definição)

Toda matriz simétrica com coeficientes reais (cujos elementos são reais) os autovalores dela necessariamente são números reais -> Não pode ser número imaginário 

Matrizes simétricas possuem multiplicidade algébrica igual a multiplicidade geométrica -> Os autovalores mesmo repetidos vão ter o número suficiente de autovetores associados a eles

(A, x, eps) -> A = matriz A; x = vetor inicial; eps = tolerância (número que vai servir para o critério de parada)
!-->